version: "1"

services:
  app:
    image: app-kasir-dbdoc
    container_name: app-kasir
    ports:
      - "9090:9090"	
    depends_on:
     - postgresdb
    
  postgresdb:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=DB_KASIR_KITA